# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0012_auto_20170831_1113'),
    ]

    operations = [
	migrations.RunSQL("CREATE INDEX idx_column ON uniqueref_gene (name)"),
    ]
