# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0013_create_table_index'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX idx_name_column ON uniqueref_screen (name)"),
    ]
